version: '3.8'
services:
  postgres:
    image: postgres:13-alpine
    container_name: pricepal-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pricepal
    ports:
      - "5431:5431"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pricepal-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  pricepal-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local